### ISSUE TITLE
Prompt to ask the user for confirmation before deleting element

### ISSUE THREAD

**Issue by IshaanShettigar** [IshaanShettigar/iDG10-GUI-Hackathon#5]
This prompt should be fired whether the user tries to delete an element whether they click on the x icon or they highlight the element by clicking on it and then press the delete key.

We can react to the `graph.remove` event listener to ask the user if they really want to remove the object (Are you sure?)

**Comment by Pragyan14** [comment]
I want to work on this issue please assign me this issue.

**Comment by IshaanShettigar** [comment]
Hey Pragyan,

Thank you so much for showing interest in contributing to my project,
before I open this project out to other contributors, I need to refactor
the code a little bit to make it more readable (Issue #1) and remove some
unnecessary files. This should be done by tomorrow or latest by Thursday.
After that, I'll get back to you and you can start working on Issue#5.

Thank you,
Ishaan Shettigar

**Comment by IshaanShettigar** [comment]
Hey, @Pragyan14 you still interested in contributing to this project? If Yes, then I'll assign you this Issue immediately and you can get started!

**Comment by Pragyan14** [comment]
Thank you for considering me for this project. However, at this time, I am not able to commit to contributing. I appreciate the opportunity and wish you all the best with the project.

**Comment by IshaanShettigar** [comment]
Not a needed feature
